Don't use six.PY2 in setup.py
six is not guaranteed to be installed before running pip/setuptools.
The client fails to install on a machine or fresh virtualenv
without six with errors like the following:

```
; virtualenv ve
; ./ve/bin/pip install riak
Collecting riak
  Downloading riak-2.5.0.tar.gz (193kB)
    100% |████████████████████████████████| 196kB 9.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ReAmHf/riak/setup.py", line 4, in <module>
        import six
    ImportError: No module named six
```

This snuck past tox testing, because six is listed as an explict
dependency in tox.ini.